version: '3.4'

services:
  mymongo_1:
    image: "mongo"
    ports:
      - 5000:27017

  demo:
    image: demo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
